In [ ]:
from dotenv import load_dotenv
import os
load_dotenv()

True

## **1.Import Libraries**

In [2]:

def change_directory(folder_name):
    
    current_path = os.getcwd()

    parent_path = os.path.dirname(current_path)

    # Change directory
    os.chdir(parent_path)
    new_path = os.path.join(parent_path,folder_name)
    if os.path.exists(new_path):
        os.chdir(new_path)
        print("Now in:", os.getcwd())
    else:
        print("Directory not found:", new_path)

In [3]:
import pandas as pd
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from transformers import DataCollatorWithPadding
from transformers import AutoTokenizer,TrainingArguments, Trainer,AutoConfig,AutoModelForSequenceClassification,pipeline
import evaluate
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import wandb
from transformers import TrainingArguments, Trainer,AutoConfig
from sentence_transformers import SentenceTransformer
import numpy as np
from huggingface_hub import notebook_login
from datasets import Dataset
from  transformers_preprocessing import *
from dotenv import load_dotenv

WARNING:tensorflow:From c:\Users\ruite\anaconda3\envs\DM2425\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

## **2. Load dataset**

In [9]:
change_directory("data")

Now in: c:\Users\ruite\OneDrive - Universidade de Lisboa\Data Science\2nd Semester\Text Mining\project\Text-Mining-Project\data

In [10]:
df_train = pd.read_csv('train.csv')

df_test = pd.read_csv('test.csv')

In [11]:
df_train['text'] = clean(df_train['text'])

df_train

100%|██████████| 9543/9543 [00:00<00:00, 22776.98it/s]

                                                   text  label
0     bynd  jpmorgan reels in expectations on beyond...      0
1     ccl rcl  nomura points to bookings weakness at...      0
2     cx  cemex cut at credit suisse jp morgan on we...      0
3     ess btig research cuts to neutral httpstcomcyf...      0
4     fnko  funko slides after piper jaffray pt cut ...      0
...                                                 ...    ...
9538  the weeks gainers and losers on the stoxx euro...      2
9539  tupperware brands among consumer gainers unile...      2
9540  vtv therapeutics leads healthcare gainers myom...      2
9541      work xpo pyx and amkr among after hour movers      2
9542               yndx i qd and oesx among tech movers      2

[9543 rows x 2 columns]

In [12]:
df_test['text'] = clean(df_test['text'])

df_test.drop(columns=['id'], inplace=True)

df_test

100%|██████████| 2388/2388 [00:00<00:00, 15146.81it/s]

                                                   text
0     etf assets to surge tenfold in years to MONETA...
1     here’s what hedge funds think evolution petrol...
2     pvh  phillipsvan heusen q3 earnings preview ht...
3     china is in the process of waiving retaliatory...
4     highlight “when growth is scarce investors see...
...                                                 ...
2383  ivc  invacare corporation ivc ceo matthew mona...
2384  domtar eps misses by MONETARYVALUESTAMP  reven...
2385  india plans incentives to bring in foreign man...
2386  nvcr shows institutional accumulation with blu...
2387  accesso technology  form   accesso technology ...

[2388 rows x 1 columns]

In [13]:
y =  df_train['label']

y

0       0
1       0
2       0
3       0
4       0
       ..
9538    2
9539    2
9540    2
9541    2
9542    2
Name: label, Length: 9543, dtype: int64

In [14]:
list_set = df_train['text'].tolist()

In [15]:
list_set = [str(i) for i in list_set]

In [16]:
sentences_df = pd.DataFrame({'sentence': list_set})

# Combine into one DataFrame
data = pd.concat([sentences_df, y], axis=1)

## **3. Train test split**

In [17]:
train_df, test_df, label_train,label_test = train_test_split(data["sentence"],data["label"],test_size=0.2, random_state=42, stratify=data['label'])

In [18]:
train_df = train_df.reset_index(drop=True)

test_df = test_df.reset_index(drop=True)

label_train = label_train.reset_index(drop=True)

label_test= label_test.reset_index(drop=True)

## **4. Models**

### **4.1 Model with Encoder Embeddings + Traditional Classifiers**

In [11]:

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to embeddings
train_embeddings = model.encode(train_df, show_progress_bar=True)

test_embeddings = model.encode(test_df, show_progress_bar=True)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/239 [00:00<?, ?it/s]

Batches:   0%|          | 0/60 [00:00<?, ?it/s]

#### 4.1.1 Logistic Regression

In [12]:

# Train a Logistic Regression on our train embeddings
clf = LogisticRegression(random_state=42)
clf.fit(train_embeddings, label_train)

LogisticRegression(random_state=42)

In [13]:

# Predict previously unseen instances
y_pred = clf.predict(test_embeddings)
labels = {"Negative":0, "Positive":1,"Neutral":2}
print(classification_report(y_pred, label_test, target_names = labels.keys()))

              precision    recall  f1-score   support

    Negative       0.61      0.77      0.68       226
    Positive       0.64      0.78      0.70       315
     Neutral       0.93      0.84      0.89      1368

    accuracy                           0.82      1909
   macro avg       0.73      0.80      0.76      1909
weighted avg       0.85      0.82      0.83      1909

#### 4.1.2 Support Vector Machines

In [14]:
svm_model = SVC(random_state=42)
svm_model.fit(train_embeddings, label_train)

SVC(random_state=42)

In [15]:
# Predict previously unseen instances
y_pred = svm_model.predict(test_embeddings)
labels = {"Negative":0, "Positive":1,"Neutral":2}
print(classification_report(y_pred, label_test, target_names = labels.keys()))

              precision    recall  f1-score   support

    Negative       0.64      0.81      0.71       225
    Positive       0.69      0.84      0.75       315
     Neutral       0.95      0.86      0.90      1369

    accuracy                           0.85      1909
   macro avg       0.76      0.84      0.79      1909
weighted avg       0.87      0.85      0.86      1909

#### 4.1.3 Multi Layer Perceptron

In [16]:
mlp_model = MLPClassifier(random_state=42)
mlp_model.fit(train_embeddings, label_train)

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(random_state=42)

In [17]:
# Predict previously unseen instances
y_pred = mlp_model.predict(test_embeddings)
labels = {"Negative":0, "Positive":1,"Neutral":2}
print(classification_report(y_pred, label_test, target_names = labels.keys()))

              precision    recall  f1-score   support

    Negative       0.69      0.75      0.72       268
    Positive       0.75      0.75      0.75       384
     Neutral       0.90      0.88      0.89      1257

    accuracy                           0.84      1909
   macro avg       0.78      0.79      0.79      1909
weighted avg       0.84      0.84      0.84      1909

### **4.2 BERT Models (with encoding and classifier embedded )**

In [19]:
train_df = pd.concat([train_df.reset_index(drop=True), label_train], axis=1)

test_df = pd.concat([test_df.reset_index(drop=True), label_test], axis=1)

In [22]:
labels = {"Negative":0, "Positive":1,"Neutral":2}

### **4.2.1 Bertweet-base-sentiment-analysis**

In [19]:

# Set up the inference pipeline using a model from the 🤗 Hub
sentiment_analysis = pipeline(model="finiteautomata/bertweet-base-sentiment-analysis")


sentiment_analysis("i love this computer")

config.json:   0%|          | 0.00/949 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/540M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/843k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.08M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0
Device set to use cuda:0

[{'label': 'POS', 'score': 0.9922279715538025}]

In [20]:
predict=[]
for sentence in tqdm(test_df['sentence'].values.tolist()):
    sentiment = sentiment_analysis(str(sentence))
    top_label = sentiment[0]['label']

    # Map label to class index
    if top_label == 'NEG':
        predict.append(0)  # negative
    elif top_label == 'NEU':
        predict.append(2)  # neutral
    elif top_label == 'POS':
        predict.append(1)  # positive

  0%|          | 0/1909 [00:00<?, ?it/s]
  0%|          | 2/1909 [00:00<01:50, 17.33it/s]
  0%|          | 7/1909 [00:00<00:59, 31.71it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

  1%|          | 11/1909 [00:00<01:04, 29.42it/s]
  1%|          | 18/1909 [00:00<00:45, 41.37it/s]
  1%|▏         | 24/1909 [00:00<00:40, 46.89it/s]
  2%|▏         | 30/1909 [00:00<00:37, 50.11it/s]
  2%|▏         | 38/1909 [00:00<00:32, 57.76it/s]
  3%|▎         | 49/1909 [00:00<00:25, 71.62it/s]
  3%|▎         | 59/1909 [00:01<00:23, 79.66it/s]
  4%|▎         | 69/1909 [00:01<00:21, 84.23it/s]
  4%|▍         | 78/1909 [00:01<00:21, 85.87it/s]
  5%|▍         | 89/1909 [00:01<00:19, 92.33it/s]
  5%|▌         | 99/1909 [00:01<00:19, 94.35it/s]
  6%|▌         | 109/1909 [00:01<00:18, 94.94it/s]
  6%|▋         | 120/1909 [00:01<00:18, 97.38it/s]
  7%|▋         | 131/1909 [00:01<00:17, 99.36it/s]
  7%|▋         | 141/1909 [00:01<00:17, 98.99it/s]
  8%|▊         | 151/1909 [00:01<00:17, 98.87it/s]
  8%|▊         | 161/1909 [00:02<00:18, 96.21it/s]
  9%|▉         | 171/1909 [00:02<00:18, 94.96it/s]
  9%|▉         | 181/1909 [00:02<00:18, 93.33it/s]
 10%|█         | 191/1909 [00:02<00:18, 94.43it/s]
 11%|█         | 201/1909 [00:02<00:17, 95.67it/s]
 11%|█         | 211/1909 [00:02<00:17, 96.69it/s]
 12%|█▏        | 221/1909 [00:02<00:17, 97.19it/s]
 12%|█▏        | 231/1909 [00:02<00:17, 96.77it/s]
 13%|█▎        | 242/1909 [00:02<00:16, 98.16it/s]
 13%|█▎        | 253/1909 [00:03<00:16, 99.08it/s]
 14%|█▍        | 264/1909 [00:03<00:16, 100.61it/s]
 14%|█▍        | 275/1909 [00:03<00:16, 98.39it/s]
 15%|█▍        | 286/1909 [00:03<00:16, 99.33it/s]
 16%|█▌        | 297/1909 [00:03<00:15, 101.33it/s]
 16%|█▌        | 308/1909 [00:03<00:15, 101.16it/s]
 17%|█▋        | 319/1909 [00:03<00:15, 101.43it/s]
 17%|█▋        | 330/1909 [00:03<00:15, 101.81it/s]
 18%|█▊        | 341/1909 [00:03<00:15, 102.12it/s]
 18%|█▊        | 352/1909 [00:03<00:15, 102.49it/s]
 19%|█▉        | 363/1909 [00:04<00:15, 101.78it/s]
 20%|█▉        | 374/1909 [00:04<00:15, 102.07it/s]
 20%|██        | 385/1909 [00:04<00:15, 98.26it/s]
 21%|██        | 396/1909 [00:04<00:15, 98.97it/s]
 21%|██▏       | 406/1909 [00:04<00:15, 99.19it/s]
 22%|██▏       | 417/1909 [00:04<00:14, 100.49it/s]
 22%|██▏       | 428/1909 [00:04<00:14, 101.12it/s]
 23%|██▎       | 439/1909 [00:04<00:14, 101.68it/s]
 24%|██▎       | 450/1909 [00:04<00:14, 102.98it/s]
 24%|██▍       | 461/1909 [00:05<00:14, 101.87it/s]
 25%|██▍       | 472/1909 [00:05<00:13, 103.35it/s]
 25%|██▌       | 483/1909 [00:05<00:13, 103.40it/s]
 26%|██▌       | 494/1909 [00:05<00:14, 97.77it/s]
 26%|██▋       | 505/1909 [00:05<00:14, 100.21it/s]
 27%|██▋       | 516/1909 [00:05<00:13, 100.40it/s]
 28%|██▊       | 527/1909 [00:05<00:13, 101.94it/s]
 28%|██▊       | 538/1909 [00:05<00:13, 102.63it/s]
 29%|██▉       | 549/1909 [00:05<00:13, 102.44it/s]
 29%|██▉       | 560/1909 [00:06<00:13, 101.20it/s]
 30%|██▉       | 571/1909 [00:06<00:12, 103.19it/s]
 30%|███       | 582/1909 [00:06<00:12, 105.00it/s]
 31%|███       | 593/1909 [00:06<00:13, 100.43it/s]
 32%|███▏      | 604/1909 [00:06<00:12, 102.24it/s]
 32%|███▏      | 615/1909 [00:06<00:12, 101.84it/s]
 33%|███▎      | 626/1909 [00:06<00:12, 102.60it/s]
 33%|███▎      | 637/1909 [00:06<00:12, 102.58it/s]
 34%|███▍      | 648/1909 [00:06<00:12, 100.88it/s]
 35%|███▍      | 659/1909 [00:07<00:12, 98.47it/s]
 35%|███▌      | 670/1909 [00:07<00:12, 100.48it/s]
 36%|███▌      | 681/1909 [00:07<00:12, 102.31it/s]
 36%|███▌      | 692/1909 [00:07<00:11, 103.05it/s]
 37%|███▋      | 703/1909 [00:07<00:12, 98.53it/s]
 37%|███▋      | 714/1909 [00:07<00:11, 99.84it/s]
 38%|███▊      | 725/1909 [00:07<00:11, 101.84it/s]
 39%|███▊      | 736/1909 [00:07<00:11, 102.16it/s]
 39%|███▉      | 747/1909 [00:07<00:11, 103.98it/s]
 40%|███▉      | 758/1909 [00:07<00:10, 104.81it/s]
 40%|████      | 769/1909 [00:08<00:11, 103.09it/s]
 41%|████      | 780/1909 [00:08<00:10, 104.13it/s]
 41%|████▏     | 791/1909 [00:08<00:10, 104.91it/s]
 42%|████▏     | 802/1909 [00:08<00:10, 102.65it/s]
 43%|████▎     | 813/1909 [00:08<00:10, 101.74it/s]
 43%|████▎     | 824/1909 [00:08<00:10, 101.88it/s]
 44%|████▎     | 835/1909 [00:08<00:10, 101.94it/s]
 44%|████▍     | 846/1909 [00:08<00:10, 101.15it/s]
 45%|████▍     | 857/1909 [00:08<00:10, 102.00it/s]
 45%|████▌     | 868/1909 [00:09<00:10, 102.97it/s]
 46%|████▌     | 879/1909 [00:09<00:09, 103.95it/s]
 47%|████▋     | 890/1909 [00:09<00:09, 104.85it/s]
 47%|████▋     | 901/1909 [00:09<00:09, 105.07it/s]
 48%|████▊     | 912/1909 [00:09<00:09, 100.81it/s]
 48%|████▊     | 923/1909 [00:09<00:09, 100.19it/s]
 49%|████▉     | 934/1909 [00:09<00:09, 102.57it/s]
 50%|████▉     | 945/1909 [00:09<00:09, 102.92it/s]
 50%|█████     | 956/1909 [00:09<00:09, 104.21it/s]
 51%|█████     | 968/1909 [00:10<00:08, 106.52it/s]
 51%|█████▏    | 979/1909 [00:10<00:08, 106.24it/s]
 52%|█████▏    | 990/1909 [00:10<00:08, 106.63it/s]
 52%|█████▏    | 1002/1909 [00:10<00:08, 108.76it/s]
 53%|█████▎    | 1013/1909 [00:10<00:08, 107.79it/s]
 54%|█████▎    | 1024/1909 [00:10<00:08, 101.97it/s]
 54%|█████▍    | 1035/1909 [00:10<00:08, 102.02it/s]
 55%|█████▍    | 1047/1909 [00:10<00:08, 103.62it/s]
 55%|█████▌    | 1058/1909 [00:10<00:09, 87.07it/s]
 56%|█████▌    | 1068/1909 [00:11<00:10, 81.15it/s]
 56%|█████▋    | 1077/1909 [00:11<00:10, 81.04it/s]
 57%|█████▋    | 1086/1909 [00:11<00:10, 78.45it/s]
 57%|█████▋    | 1095/1909 [00:11<00:10, 77.79it/s]
 58%|█████▊    | 1103/1909 [00:11<00:10, 74.93it/s]
 58%|█████▊    | 1111/1909 [00:11<00:10, 74.59it/s]
 59%|█████▊    | 1119/1909 [00:11<00:10, 74.16it/s]
 59%|█████▉    | 1127/1909 [00:11<00:10, 75.44it/s]
 59%|█████▉    | 1135/1909 [00:11<00:10, 76.27it/s]
 60%|█████▉    | 1143/1909 [00:12<00:09, 76.80it/s]
 60%|██████    | 1152/1909 [00:12<00:09, 78.65it/s]
 61%|██████    | 1161/1909 [00:12<00:09, 80.08it/s]
 61%|██████▏   | 1170/1909 [00:12<00:09, 74.63it/s]
 62%|██████▏   | 1178/1909 [00:12<00:10, 72.16it/s]
 62%|██████▏   | 1186/1909 [00:12<00:10, 71.26it/s]
 63%|██████▎   | 1194/1909 [00:12<00:10, 67.65it/s]
 63%|██████▎   | 1201/1909 [00:12<00:10, 67.83it/s]
 63%|██████▎   | 1208/1909 [00:13<00:10, 65.69it/s]
 64%|██████▎   | 1215/1909 [00:13<00:10, 64.39it/s]
 64%|██████▍   | 1223/1909 [00:13<00:10, 68.46it/s]
 65%|██████▍   | 1234/1909 [00:13<00:08, 78.09it/s]
 65%|██████▌   | 1244/1909 [00:13<00:07, 83.79it/s]
 66%|██████▌   | 1254/1909 [00:13<00:07, 86.96it/s]
 66%|██████▌   | 1264/1909 [00:13<00:07, 90.01it/s]
 67%|██████▋   | 1274/1909 [00:13<00:07, 90.61it/s]
 67%|██████▋   | 1285/1909 [00:13<00:06, 95.05it/s]
 68%|██████▊   | 1296/1909 [00:13<00:06, 97.16it/s]
 68%|██████▊   | 1306/1909 [00:14<00:06, 96.67it/s]
 69%|██████▉   | 1317/1909 [00:14<00:05, 98.91it/s]
 70%|██████▉   | 1328/1909 [00:14<00:05, 100.18it/s]
 70%|███████   | 1339/1909 [00:14<00:05, 100.77it/s]
 71%|███████   | 1350/1909 [00:14<00:05, 100.56it/s]
 71%|███████▏  | 1361/1909 [00:14<00:06, 90.90it/s]
 72%|███████▏  | 1371/1909 [00:14<00:06, 89.55it/s]
 72%|███████▏  | 1382/1909 [00:14<00:05, 94.26it/s]
 73%|███████▎  | 1392/1909 [00:14<00:05, 95.28it/s]
 73%|███████▎  | 1403/1909 [00:15<00:05, 97.63it/s]
 74%|███████▍  | 1414/1909 [00:15<00:04, 100.38it/s]
 75%|███████▍  | 1425/1909 [00:15<00:04, 102.66it/s]
 75%|███████▌  | 1436/1909 [00:15<00:04, 102.46it/s]
 76%|███████▌  | 1447/1909 [00:15<00:04, 103.87it/s]
 76%|███████▋  | 1458/1909 [00:15<00:04, 103.11it/s]
 77%|███████▋  | 1469/1909 [00:15<00:04, 102.09it/s]
 78%|███████▊  | 1480/1909 [00:15<00:04, 97.68it/s]
 78%|███████▊  | 1490/1909 [00:15<00:04, 97.75it/s]
 79%|███████▊  | 1500/1909 [00:16<00:04, 95.70it/s]
 79%|███████▉  | 1510/1909 [00:16<00:04, 95.17it/s]
 80%|███████▉  | 1520/1909 [00:16<00:04, 95.10it/s]
 80%|████████  | 1530/1909 [00:16<00:04, 94.47it/s]
 81%|████████  | 1541/1909 [00:16<00:03, 97.47it/s]
 81%|████████  | 1551/1909 [00:16<00:03, 96.79it/s]
 82%|████████▏ | 1561/1909 [00:16<00:03, 97.61it/s]
 82%|████████▏ | 1571/1909 [00:16<00:03, 96.16it/s]
 83%|████████▎ | 1582/1909 [00:16<00:03, 97.87it/s]
 83%|████████▎ | 1593/1909 [00:17<00:03, 100.36it/s]
 84%|████████▍ | 1604/1909 [00:17<00:03, 100.61it/s]
 85%|████████▍ | 1615/1909 [00:17<00:02, 102.15it/s]
 85%|████████▌ | 1626/1909 [00:17<00:02, 102.99it/s]
 86%|████████▌ | 1637/1909 [00:17<00:02, 103.35it/s]
 86%|████████▋ | 1648/1909 [00:17<00:02, 104.80it/s]
 87%|████████▋ | 1659/1909 [00:17<00:02, 104.85it/s]
 87%|████████▋ | 1670/1909 [00:17<00:02, 105.24it/s]
 88%|████████▊ | 1681/1909 [00:17<00:02, 100.40it/s]
 89%|████████▊ | 1692/1909 [00:17<00:02, 101.79it/s]
 89%|████████▉ | 1703/1909 [00:18<00:02, 102.32it/s]
 90%|████████▉ | 1714/1909 [00:18<00:01, 103.99it/s]
 90%|█████████ | 1725/1909 [00:18<00:01, 104.58it/s]
 91%|█████████ | 1736/1909 [00:18<00:01, 105.33it/s]
 92%|█████████▏| 1748/1909 [00:18<00:01, 107.52it/s]
 92%|█████████▏| 1759/1909 [00:18<00:01, 105.55it/s]
 93%|█████████▎| 1770/1909 [00:18<00:01, 106.13it/s]
 93%|█████████▎| 1781/1909 [00:18<00:01, 104.86it/s]
 94%|█████████▍| 1792/1909 [00:18<00:01, 100.84it/s]
 94%|█████████▍| 1803/1909 [00:19<00:01, 103.37it/s]
 95%|█████████▌| 1814/1909 [00:19<00:00, 104.41it/s]
 96%|█████████▌| 1825/1909 [00:19<00:00, 103.81it/s]
 96%|█████████▌| 1837/1909 [00:19<00:00, 106.23it/s]
 97%|█████████▋| 1848/1909 [00:19<00:00, 106.77it/s]
 97%|█████████▋| 1859/1909 [00:19<00:00, 105.47it/s]
 98%|█████████▊| 1871/1909 [00:19<00:00, 107.43it/s]
 99%|█████████▊| 1882/1909 [00:19<00:00, 107.49it/s]
 99%|█████████▉| 1893/1909 [00:19<00:00, 104.98it/s]
100%|██████████| 1909/1909 [00:20<00:00, 95.17it/s]

In [ ]:

print(classification_report(predict, test_df['label'].values.tolist(), target_names = labels.keys()))

              precision    recall  f1-score   support

    Negative       0.59      0.45      0.51       378
    Positive       0.30      0.47      0.37       247
     Neutral       0.74      0.71      0.72      1284

    accuracy                           0.63      1909
   macro avg       0.54      0.54      0.53      1909
weighted avg       0.65      0.63      0.63      1909

In [22]:
train_df

                                               sentence  label
0         nasdaq prices 600m of PERCENTAGE senior notes      2
1                         futures up httpstcodiz7v5lmvb      1
2     econx november nonfarm private payrolls 125k v...      0
3     twitter users explain why kohls stock just got...      0
4     agilysys  restaurants find sustainable methods...      2
...                                                 ...    ...
7629                   japan tobacco reports fy results      2
7630  the feds emergence as a power player poses new...      2
7631  how the rise of athome fitness services could ...      1
7632           daniel loebs top buys in the 3rd quarter      2
7633  zee entertainment’s subhash chandra resigns as...      2

[7634 rows x 2 columns]

### **4.2.2 Fine tuning a pre trained model**

In [ ]:


def compute_metrics(p):
    preds = p.predictions.argmax(-1)
    labels = p.label_ids
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average="weighted"),
        "precision": precision_score(labels, preds, average="weighted"),
        "recall": recall_score(labels, preds, average="weighted"),
    }

Insert the below token on notebook login

In [7]:
token= os.getenv("HF_TOKEN")

token

'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'

In [37]:
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [26]:
model_path = 'ProsusAI/finbert'

In [27]:
label2id = {label: idx for idx, label in labels.items()}

config = AutoConfig.from_pretrained(
    model_path,
    num_labels=len(labels),
    id2label=label2id,
    label2id=labels
)

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

In [28]:
tokenizer = AutoTokenizer.from_pretrained(model_path)

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [29]:
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

In [30]:
train_dataset

Dataset({
    features: ['sentence', 'label'],
    num_rows: 7634
})

In [31]:
def preprocess_function(examples):
   return tokenizer(examples['sentence'], truncation=True)

tokenized_train = train_dataset.map(preprocess_function)
tokenized_test = test_dataset.map(preprocess_function)

Map:   0%|          | 0/7634 [00:00<?, ? examples/s]

Map:   0%|          | 0/1909 [00:00<?, ? examples/s]

In [32]:
tokenized_train

Dataset({
    features: ['sentence', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 7634
})

In [33]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [34]:
labels = {"negative":0, "Positive":1,"Neutral":2}

#### **4.2.2.1 Create Model on Hugging Face**

In [38]:

model = AutoModelForSequenceClassification.from_pretrained(model_path,config=config)


repo_name = "finetuning-sentiment-model"

training_args = TrainingArguments(
   output_dir=repo_name,
   learning_rate=2e-5,
   per_device_train_batch_size=16,
   per_device_eval_batch_size=16,
   num_train_epochs=2,
   weight_decay=0.01,
   save_strategy="epoch",
   push_to_hub=True,
)

trainer = Trainer(
   model=model,
   args=training_args,
   train_dataset=tokenized_train,
   eval_dataset=tokenized_test,
   tokenizer=tokenizer,
   data_collator=data_collator,
   compute_metrics=compute_metrics,
)

<ipython-input-38-1473146300>:17: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Insert trainer_key on train method

In [6]:
trainer_key=os.getenv("TRAIN_TOKEN")

trainer_key

'6f806eda47fd4c0751f7f969256f26072a66cd17'

In [39]:

# Initialize a new W&B run
wandb.init(project="finetuning-sentiment-model")

train_result = trainer.train()

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: ruitenjua24 (ruitenjua24-nova-ims-su) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

In [41]:
trainer.evaluate()

{'eval_loss': 0.4471156895160675,
 'eval_accuracy': 0.8501833420639078,
 'eval_f1': 0.8484949669134726,
 'eval_precision': 0.8475476256963193,
 'eval_recall': 0.8501833420639078,
 'eval_runtime': 4.5616,
 'eval_samples_per_second': 418.491,
 'eval_steps_per_second': 26.306,
 'epoch': 2.0}

In [42]:
trainer.push_to_hub()

Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/ruitj/finetuning-sentiment-model/commit/a0740334c2613cb83b3562dfedc1db25a12d536f', commit_message='End of training', commit_description='', oid='a0740334c2613cb83b3562dfedc1db25a12d536f', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ruitj/finetuning-sentiment-model', endpoint='https://huggingface.co', repo_type='model', repo_id='ruitj/finetuning-sentiment-model'), pr_revision=None, pr_num=None)

#### **4.2.2.2 Use our fined tuned model**

Fine tunning of Finbert available at [Hugging Face Model](https://huggingface.co/ruitj/finetuning-sentiment-model)

In [20]:
sentiment_model = pipeline(model="ruitj/finetuning-sentiment-model")

sentiment_model(["futures are up"])

config.json:   0%|          | 0.00/845 [00:00<?, ?B/s]

c:\Users\ruite\anaconda3\envs\DM2425\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ruite\.cache\huggingface\hub\models--ruitj--finetuning-sentiment-model. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.27k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cpu

[{'label': 'Positive', 'score': 0.9661130309104919}]

In [24]:
predict=[]
for sentence in tqdm(test_df['sentence'].values.tolist()):
    sentiment = sentiment_model(str(sentence))
    top_label = sentiment[0]['label']

    # Map label to class index
    if top_label == 'Positive':
        predict.append(1)  # negative
    elif top_label == 'Negative':
        predict.append(0)  # neutral
    elif top_label == 'Neutral':
        predict.append(2)  # positive

100%|██████████| 1909/1909 [02:35<00:00, 12.30it/s]

In [25]:

print(classification_report(predict,test_df['label'].values.tolist() , target_names = labels.keys()))

              precision    recall  f1-score   support

    Negative       0.68      0.71      0.70       276
    Positive       0.74      0.79      0.76       359
     Neutral       0.92      0.90      0.91      1274

    accuracy                           0.85      1909
   macro avg       0.78      0.80      0.79      1909
weighted avg       0.85      0.85      0.85      1909

In [27]:
predict=[]
for sentence in tqdm(df_test['text'].values.tolist()):
    sentiment = sentiment_model(str(sentence))
    top_label = sentiment[0]['label']

    # Map label to class index
    if top_label == 'Positive':
        predict.append(1)  # negative
    elif top_label == 'Negative':
        predict.append(0)  # neutral
    elif top_label == 'Neutral':
        predict.append(2)  # positive

100%|██████████| 2388/2388 [03:21<00:00, 11.88it/s]

In [28]:
test_final = pd.concat([df_test['text'].reset_index(drop=True), pd.DataFrame(predict)], axis=1)

In [30]:
change_directory("predictions")

Now in: c:\Users\ruite\OneDrive - Universidade de Lisboa\Data Science\2nd Semester\Text Mining\project\Text-Mining-Project\predictions

In [31]:
test_final.to_csv('predictions_tests_01_31.csv')